### ISSUE TITLE
Make wires thinner

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#18]
From @ariel-phet:

>  1. Since we are not showing the electron representation, it seems the wires should be thinner (it seemed there was some concern about students confusing wires and resistors...a real world wire is quite a bit thinner and that would help I think). It might be more pixel polish land, but if it looked a bit more "coppery" it might also be good to differentiate it from the resistor. Resistors also tend to be more "tan" http://images.wisegeek.com/tan-fixed-resistors.jpg

**Comment by samreid** [comment]
I sampled a color from http://www.maneywire.com/images/products/BARE%20COPPER.jpg
![image](https://cloud.githubusercontent.com/assets/679486/14047940/a82114a0-f270-11e5-846e-2f8a0806e23c.png)

But not sure it looks as good without shading and other contextual cues.

**Comment by samreid** [comment]
I made the wires thinner in the above commit, now it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/14048175/2d1ef7ac-f272-11e5-8348-b4be91eb617e.png)

@ariel-phet can you review and comment?

**Comment by ariel-phet** [comment]
Thinness looks better.

I have to say...if possible, I think think have some gradient on the wire to make it look "shiny" would be nice. Perhaps a color closer to the "copper" end of the battery? Again, I know this is the realm of pixel polishing, but seems valuable since students apparently needed to differentiate wire and resistor more.

**Comment by samreid** [comment]
Since the wire thinness looks better, I'll close this issue.  The color/gradient will be tracked in #42
