### ISSUE TITLE
The overlay makes it difficult to compare bulb brightness

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#46]
I chose an aggressive overlay to make it clear the "build" focus should be inside the black box.  However, this makes it very difficult to distinguish changes in brightness of the light bulb.  I suspect any non-trivial overlay would obscure the change in bulb brightness.

Investigate:
![image](https://cloud.githubusercontent.com/assets/679486/14131553/b0970d74-f5f9-11e5-9625-ad60ba7dce48.png)

Build:
![image](https://cloud.githubusercontent.com/assets/679486/14131559/b90b1ef0-f5f9-11e5-859c-1bc6445b8669.png)

@arouinfar can you think about the interplay between the transparency overlay and how it will impact interpretation of light bulb brightness?  How to proceed?

**Comment by arouinfar** [comment]
@samreid, the transparency overlay feels a bit too dark to me. Since the bulb brightness is proportional to the ray length, I don't think it will be difficult for students to interpret the brightness behind the screen, so long as it is transparent enough.  I can think of two alternatives.
* Try a white overlay with 50% opacity (as done in the mockups). The white screen may obscure the light a bit less.
* Try reducing the opacity of the black overlay by 20% or so and see if that helps.

**Comment by samreid** [comment]
Here's the look in "investigate":

![image](https://cloud.githubusercontent.com/assets/679486/14152813/3552aa46-f672-11e5-9c8c-3b35e10661c8.png)

Here's with `{ fill: 'white', opacity: 0.5 }`

![image](https://cloud.githubusercontent.com/assets/679486/14152828/4f9298d0-f672-11e5-9ab4-b8d0558a3f74.png)

I'll commit and @arouinfar can take it for a test drive.

**Comment by samreid** [comment]
It's committed above, @arouinfar can you test master and report back?

**Comment by arouinfar** [comment]
Thanks @samreid! I'll pull the latest from phettest and take a look.

**Comment by arouinfar** [comment]
Looks good @samreid! I think the ray-length is easily interpretable beneath the white transparency, while the bulb itself is clearly non-interactive (can't be moved/deleted).

**Comment by samreid** [comment]
Thanks for reviewing, I'll close the issue.
