### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#60]
@arouinfar can you please document the credits and make a note of it here in the issue?

**Comment by arouinfar** [comment]
@samreid here are the credits:
Amy Rouinfar (lead designer)
Michael Dubson
Ariel Paul
Kathy Perkins
Sam Reid (developer)
Bryce Gruneich (graphic arts) 

For ports, we typically also credit the original design team. I don't think that applies to CCK: Black Box, since it is not really a redesign of Java CCK. CCK: Basics seems like a more appropriate place to credit the original team.

**Comment by samreid** [comment]
Thanks @arouinfar, I've added that part.
